spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/mspring
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 5000
  security:
    user:
      name: user
      password: 1234
  #开发者工具
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
server:
  port: 8081
  ssl:
    key-store: classpath:km.p12
    key-store-password: 123456
    key-alias: serverkey